### ISSUE TITLE
Hauptmenü erstellen

### ISSUE THREAD

**Issue by Maxi739** [Diplomarbeit-Team-5DHK/Sequence-Unity#1]
Ein Hauptmenü erstellen (Basic), Alle Buttons Zuweisen

**Comment by Jakobxml** [comment]
Das ist der Start des Spiels, ein einfaches Hauptmenü bestehend aus Buttons, die dafür sorgen, dass der Spieler sich einen Spielmodi aussuchen kann mit Multiplayer.
